/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TodoApp.view;

import TodoApp.controller.UserController;
import TodoApp.model.User;
import java.util.Arrays;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Deijigue
 */
public class LoginScreen extends javax.swing.JFrame {

    private UserController userController;
    private User user;
    /**
     * Creates new form SignUpScreen
     */
    public LoginScreen() {
        initComponents();
        hideErrorLabels();
        userController = new UserController();
        decorateWindow();
    }

    private void decorateWindow() {
        setIconImage(new ImageIcon(getClass().getResource("/tick.png")).getImage());
        setTitle("Todo App");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainerSignUp = new javax.swing.JPanel();
        jPanelSignUp = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelEmailError = new javax.swing.JLabel();
        jLabelPasswordError = new javax.swing.JLabel();
        jPanelButtonLogin = new javax.swing.JPanel();
        jLabelButtonLogin = new javax.swing.JLabel();
        jLabelBoxTitle = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelCredentialsError = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 750));

        jPanelContainerSignUp.setBackground(new java.awt.Color(0, 153, 102));

        jPanelSignUp.setBackground(java.awt.Color.white);

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail.setText("e-mail");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword.setText("senha");

        jLabelEmailError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmailError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelEmailError.setText("Campo de e-mail obrigatório");

        jLabelPasswordError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelPasswordError.setText("Campo de senha obrigatório");

        jPanelButtonLogin.setBackground(new java.awt.Color(0, 153, 102));

        jLabelButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelButtonLogin.setForeground(java.awt.Color.white);
        jLabelButtonLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonLogin.setText("Login");
        jLabelButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLoginLayout = new javax.swing.GroupLayout(jPanelButtonLogin);
        jPanelButtonLogin.setLayout(jPanelButtonLoginLayout);
        jPanelButtonLoginLayout.setHorizontalGroup(
            jPanelButtonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelButtonLoginLayout.setVerticalGroup(
            jPanelButtonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelBoxTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelBoxTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelBoxTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoxTitle.setText("Efetue Login");

        jLabelCredentialsError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCredentialsError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelCredentialsError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCredentialsError.setText("Credenciais inválidas");

        javax.swing.GroupLayout jPanelSignUpLayout = new javax.swing.GroupLayout(jPanelSignUp);
        jPanelSignUp.setLayout(jPanelSignUpLayout);
        jPanelSignUpLayout.setHorizontalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBoxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButtonLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCredentialsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanelSignUpLayout.setVerticalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBoxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPasswordError)
                .addGap(18, 18, 18)
                .addComponent(jPanelButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCredentialsError)
                .addGap(62, 62, 62))
        );

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelTitle.setForeground(java.awt.Color.white);
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabelTitle.setText(" Todo App");

        jLabelSignUp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSignUp.setForeground(java.awt.Color.white);
        jLabelSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignUp.setText("Não possui conta? Cadastre-se");
        jLabelSignUp.setMaximumSize(new java.awt.Dimension(37, 32));
        jLabelSignUp.setMinimumSize(new java.awt.Dimension(37, 32));
        jLabelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSignUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerSignUpLayout = new javax.swing.GroupLayout(jPanelContainerSignUp);
        jPanelContainerSignUp.setLayout(jPanelContainerSignUpLayout);
        jPanelContainerSignUpLayout.setHorizontalGroup(
            jPanelContainerSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContainerSignUpLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelContainerSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addComponent(jPanelSignUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        jPanelContainerSignUpLayout.setVerticalGroup(
            jPanelContainerSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerSignUpLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanelSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelContainerSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanelContainerSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLoginMouseClicked
        // TODO add your handling code here:
        try {
            
            User user = null;
            
            if (!inputsAreBlank()) {

                user = userController.getByEmail(jTextFieldEmail.getText());
                if (user == null) {
                    //JOptionPane.showMessageDialog(rootPane, message);
                    hideErrorLabels();
                    showErrorLabel(jLabelCredentialsError);
                    return;
                }
                
                if (!user.getPassword().equals(new String(jPasswordFieldPassword.getPassword()))) {
                    //JOptionPane.showMessageDialog(rootPane, message);
                    hideErrorLabels();
                    showErrorLabel(jLabelCredentialsError);
                    return;
                }
                
                this.user = user;
                goToMainScreen();

            } else {
                
                hideErrorLabels();
                if ("".equals(jTextFieldEmail.getText())) {
                    showErrorLabel(jLabelEmailError);
                }
                
                if (jPasswordFieldPassword.getPassword().length == 0) {
                    showErrorLabel(jLabelPasswordError);
                }
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jLabelButtonLoginMouseClicked

    private void jLabelSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignUpMouseClicked
        // TODO add your handling code here:
        goToSignUpScreen();
    }//GEN-LAST:event_jLabelSignUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBoxTitle;
    private javax.swing.JLabel jLabelButtonLogin;
    private javax.swing.JLabel jLabelCredentialsError;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailError;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPasswordError;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtonLogin;
    private javax.swing.JPanel jPanelContainerSignUp;
    private javax.swing.JPanel jPanelSignUp;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables

    private void showErrorLabel(JLabel jLabel) {
        jLabel.setVisible(true);
    }
    
    private void hideErrorLabels() {
        jLabelEmailError.setVisible(false);
        jLabelPasswordError.setVisible(false);
        jLabelCredentialsError.setVisible(false);
    }

    private boolean inputsAreBlank() {
        return "".equals(jTextFieldEmail.getText())
                || jPasswordFieldPassword.getPassword().length == 0;
    }

    private void goToSignUpScreen() {
        SignUpScreen signUpScreen = new SignUpScreen();
        signUpScreen.setVisible(true);
        this.dispose();
    }

    private void goToMainScreen() {
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        mainScreen.setAuthUser(this.user);
        this.dispose();
    }
}
