/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TodoApp.view;

import TodoApp.controller.UserController;
import TodoApp.model.User;
import java.util.Arrays;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Deijigue
 */
public class SignUpScreen extends javax.swing.JFrame {

    private UserController userController;
    /**
     * Creates new form SignUpScreen
     */
    public SignUpScreen() {
        initComponents();
        hideErrorLabels();
        userController = new UserController();
        decorateWindow();
    }

    private void decorateWindow() {
        setIconImage(new ImageIcon(getClass().getResource("/tick.png")).getImage());
        setTitle("Todo App");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainerSignUp = new javax.swing.JPanel();
        jPanelSignUp = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelPasswordConfirmation = new javax.swing.JLabel();
        jLabelNameError = new javax.swing.JLabel();
        jLabelPasswordError = new javax.swing.JLabel();
        jPanelButtonSignUp = new javax.swing.JPanel();
        jLabelButtonSignUp = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelBoxTitle = new javax.swing.JLabel();
        jPasswordFieldPasswordConfirmation = new javax.swing.JPasswordField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelEmailError = new javax.swing.JLabel();
        jLabelPasswordConfirmationError = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 750));

        jPanelContainerSignUp.setBackground(new java.awt.Color(0, 153, 102));

        jPanelSignUp.setBackground(java.awt.Color.white);

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setText("nome");

        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail.setText("e-mail");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword.setText("senha");

        jLabelPasswordConfirmation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPasswordConfirmation.setText("confirmar senha");

        jLabelNameError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNameError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNameError.setText("Campo de nome obrigatório");

        jLabelPasswordError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelPasswordError.setText("Campo de senha obrigatório");

        jPanelButtonSignUp.setBackground(new java.awt.Color(0, 153, 102));

        jLabelButtonSignUp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelButtonSignUp.setForeground(java.awt.Color.white);
        jLabelButtonSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonSignUp.setText("Cadastre-se");
        jLabelButtonSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonSignUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonSignUpLayout = new javax.swing.GroupLayout(jPanelButtonSignUp);
        jPanelButtonSignUp.setLayout(jPanelButtonSignUpLayout);
        jPanelButtonSignUpLayout.setHorizontalGroup(
            jPanelButtonSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelButtonSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelButtonSignUpLayout.setVerticalGroup(
            jPanelButtonSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelButtonSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelBoxTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelBoxTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelBoxTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoxTitle.setText("Faça seu Cadastro");

        jLabelEmailError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmailError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelEmailError.setText("Campo de e-mail obrigatório");

        jLabelPasswordConfirmationError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPasswordConfirmationError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelPasswordConfirmationError.setText("As senhas não coincidem");

        javax.swing.GroupLayout jPanelSignUpLayout = new javax.swing.GroupLayout(jPanelSignUp);
        jPanelSignUp.setLayout(jPanelSignUpLayout);
        jPanelSignUpLayout.setHorizontalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBoxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPasswordConfirmation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPasswordConfirmation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButtonSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPasswordConfirmationError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanelSignUpLayout.setVerticalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBoxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPasswordError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPasswordConfirmation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPasswordConfirmationError)
                .addGap(23, 23, 23)
                .addComponent(jPanelButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelTitle.setForeground(java.awt.Color.white);
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabelTitle.setText(" Todo App");

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelLogin.setForeground(java.awt.Color.white);
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("Já é usuário? Login");
        jLabelLogin.setMaximumSize(new java.awt.Dimension(37, 32));
        jLabelLogin.setMinimumSize(new java.awt.Dimension(37, 32));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerSignUpLayout = new javax.swing.GroupLayout(jPanelContainerSignUp);
        jPanelContainerSignUp.setLayout(jPanelContainerSignUpLayout);
        jPanelContainerSignUpLayout.setHorizontalGroup(
            jPanelContainerSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContainerSignUpLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelContainerSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addComponent(jPanelSignUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        jPanelContainerSignUpLayout.setVerticalGroup(
            jPanelContainerSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerSignUpLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanelSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelContainerSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanelContainerSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonSignUpMouseClicked
        // TODO add your handling code here:
        try {
            
            User user = null;
            
            if (!"".equals(jTextFieldEmail.getText())) {
                
                user = userController.getByEmail(jTextFieldEmail.getText());
                if (user != null) {
                    JOptionPane.showMessageDialog(rootPane, "E-mail já é cadastrado");
                    return;
                }
                
            }
            
            if (!inputsAreBlank() && passwordsMatch()) {

                user = new User();
                
                user.setName(jTextFieldName.getText());
                user.setEmail(jTextFieldEmail.getText());
                user.setPassword(new String(jPasswordFieldPassword.getPassword()));

                userController.save(user);
                goToLoginScreen();

            } else {
                
                hideErrorLabels();
                if ("".equals(jTextFieldName.getText())) {
                    showErrorLabel(jLabelNameError);
                }
                
                if ("".equals(jTextFieldEmail.getText())) {
                    showErrorLabel(jLabelEmailError);
                }
                
                if (jPasswordFieldPassword.getPassword().length == 0) {
                    showErrorLabel(jLabelPasswordError);
                }
                
                if (!passwordsMatch()) {
                    showErrorLabel(jLabelPasswordConfirmationError);
                }
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jLabelButtonSignUpMouseClicked

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        // TODO add your handling code here:
        goToLoginScreen();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBoxTitle;
    private javax.swing.JLabel jLabelButtonSignUp;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailError;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameError;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPasswordConfirmation;
    private javax.swing.JLabel jLabelPasswordConfirmationError;
    private javax.swing.JLabel jLabelPasswordError;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtonSignUp;
    private javax.swing.JPanel jPanelContainerSignUp;
    private javax.swing.JPanel jPanelSignUp;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JPasswordField jPasswordFieldPasswordConfirmation;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    private void showErrorLabel(JLabel jLabel) {
        jLabel.setVisible(true);
    }
    
    private void hideErrorLabels() {
        jLabelNameError.setVisible(false);
        jLabelEmailError.setVisible(false);
        jLabelPasswordError.setVisible(false);
        jLabelPasswordConfirmationError.setVisible(false);
    }

    private boolean passwordsMatch() {
        return Arrays.equals(jPasswordFieldPassword.getPassword(), jPasswordFieldPasswordConfirmation.getPassword());
    }

    private boolean inputsAreBlank() {
        return "".equals(jTextFieldName.getText())
                || "".equals(jTextFieldEmail.getText())
                || jPasswordFieldPassword.getPassword().length == 0;
    }

    private void goToLoginScreen() {
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
        this.dispose();
    }
}
